export const nswAgencies = [
    'NSW Aboriginal Land Council',
    'Department of Premier and Cabinet',
    'NSW Electoral Commission',
    'Aboriginal Affairs NSW',
    'NSW Ombudsman’s Office',
    'Art Gallery of NSW',
    'NSW State Archives and Records',
    'Australian Museum',
    'Parliamentary Counsel’s Office',
    'Greater Sydney Commission',
    'Public Service Commission',
    'Independent Commission Against Corruption',
    'State Library of NSW',
    'Infrastructure NSW',
    'Sydney Living Museums',
    'Law Enforcement Conduct Commission',
    'Sydney Opera House Trust',
    'Museum of Applied Arts & Sciences',
    'The Audit Office of NSW',
    'NSW Treasury',
    'NSW Treasury Corporation',
    'Cobbora Holding Company',
    'Revenue NSW',
    'Destination NSW',
    'SAS Trustee Corporation',
    'FSS Trustee Corporation',
    'Insurance and Care NSW (icare)',
    'Roads and Maritime Services',
    'Transport for NSW',
    'State Transit Authority',
    'NSW TrainLink',
    'Sydney Motorway Corporation',
    'Office of the NSW Point to Point',
    'Transport Commissioner',
    'Sydney Trains',
    'Port Authority of New South Wales',
    'Planning Industry & Environment cluster',
    'Department of Planning, Industry',
    'Hunter Local Land Services & Environment',
    'Hunter Water Corporation',
    'Cemeteries and Crematoria NSW',
    'Landcom',
    'Centennial Parklands',
    'Murray Local Land Services',
    'Central Tablelands Local Land Services',
    'Natural Resources Access Regulator',
    'Central West Local Land Services',
    'NSW Food Authority',
    'Environment Protection Authority',
    'NSW Aboriginal Housing Office',
    'Essential Energy',
    'NSW Land and Housing Corporation',
    'Forestry Corporation NSW',
    'NSW Local Land Services (executive)',
    'Greater Sydney Local Land Services',
    'NSW Rural Assistance Authority',
    'Hunter and Central Coast Development Corporation',
    'North Coast Local Land Services',
    'NSW State Archives and Records',
    'Northern Tablelands Local Land',
    'Sydney Olympic Park Authority Services',
    'Sydney Water',
    'North West Local Land Services',
    'Taronga Conservation Society of Australia',
    'Property NSW',
    'Riverina Local Land Services',
    'Water NSW',
    'Royal Botanic Gardens Trust',
    'Western Local Land Services',
    'South East Local Land Services',
    'Department of Customer Service',
    'NSW Land Registry Service',
    'NSW Telco Authority',
    'Independent Liquor & Gaming Authority',
    'Office of the Registrar General',
    'Independent Pricing and Regulatory',
    'Office of the Valuer General Tribunal (IPART)',
    'Registry of Births Deaths & Marriages',
    'Information and Privacy Commission',
    'Service NSW',
    'Long Service Corporation',
    'State Insurance Regulatory Authority',
    'Department of Communities & Justice',
    'NSW Police Force',
    'NSW Rural Fire Service',
    'Advocate for Children and Young People',
    'NSW State Emergency Service',
    'NSW State Parole Authority',
    'Anti-Discrimination Board',
    'NSW Trustee & Guardian',
    'Bureau of Crime Statistics and Research',
    'Office of Sport',
    'Corrective Services NSW',
    'Office of the Children’s Guardian',
    'Crown Solicitor’s Office',
    'Office of the Director of Public Prosecutions',
    'Fire and Rescue NSW',
    'Office of the Legal Services',
    'Judicial Commission of NSW',
    'Juvenile Justice',
    'Office of the Sheriff of NSW',
    'Legal Aid NSW',
    'Sydney Cricket & Sports Ground Trust',
    'Multicultural NSW',
    'Venues NSW',
    'NSW Crime Commission',
    'NSW Institute of Sport',
    'Ministry of Health',
    'Clinical Excellence Commission',
    'Agency for Clinical Innovation',
    'Health Care Complaints Commission',
    'Ambulance Service of NSW',
    'Health Education and Training Institute',
    'Bureau of Health Information',
    'Health Professionals Council Authority',
    'Cancer Institute of NSW',
    'Justice Health & Forensic Mental Health Network',
    'NSW State Archives and Records',
    'Mental Health Commission of NSW',
    'Sydney Children’s Hospital Network',
    'St Vincent’s Health Network',
    'Department of Education',
    'NSW Educational Standards Authority',
    'Australian Children’s Education and TAFE NSW',
    'Care Quality Authority',
    'Central Coast LHD',
    'Northern Sydney LHD',
    'Far West LHD',
    'South Eastern Sydney LHD',
    'Hunter New England LHD',
    'South Western Sydney LHD',
    'Illawarra Shoalhaven LHD',
    'Southern NSW LHD',
    'Mid North Coast LHD',
    'Sydney LHD',
    'Murrumbidgee LHD',
    'Western NSW LHD',
    'Nepean Blue Mountains LHD',
    'Western Sydney LHD',
    'Northern NSW LHD',
    'Charles Sturt University',
    'University of New South Wales',
    'Macquarie University',
    'University of Technology, Sydney',
    'Southern Cross University',
    'University of Wollongong',
    'The University of Sydney',
    'Western Sydney University',
    'University of Newcastle',
    'University of New England',
    'Albury City Council',
    'Brewarrina Shire Council',
    'Armidale Regional Council',
    'Broken Hill City Council',
    'Ballina Shire Council',
    'Burwood Council',
    'Balranald Shire Council',
    'Byron Shire Council',
    'Bathurst Regional Council',
    'Cabonne Council',
    'Bayside Council',
    'Camden Council',
    'Bega Valley Shire Council',
    'Campbelltown City Council',
    'Bellingen Shire Council',
    'Canterbury-Bankstown Council',
    'Berrigan Shire Council',
    'Carrathool Shire Council',
    'Blacktown City Council',
    'Castlereagh Macquarie County Council',
    'Bland Shire Council',
    'Central Coast Council',
    'Blayney Shire Council',
    'Central Darling Shire Council',
    'Blue Mountains City Council',
    'Central Murray County Council',
    'Bogan Shire Council',
    'Central Tablelands Water',
    'Bourke Shire Council',
    'Cessnock City Council',
    'City of Canada Bay Council',
    'Kyogle Council',
    'City of Lithgow',
    'Lachlan Shire Council',
    'City of Parramatta',
    'Lake Macquarie City Council',
    'City of Sydney',
    'Lane Cove Council',
    'Clarence Valley Council',
    'Leeton Shire Council',
    'Cobar Shire Council',
    'Lismore City Council',
    'Coffs Harbour City Council',
    'Liverpool City Council',
    'Coolamon Shire Council',
    'Liverpool Plains Shire Council',
    'Coonamble Shire Council',
    'Lockhart Shire Council',
    'Cootamundra-Gundagai Regional Council',
    'Maitland City Council',
    'MidCoast Council',
    'Council of the City of Ryde',
    'Mid-Western Regional Council',
    'Cowra Shire Council',
    'Moree Plains Shire Council',
    'Cumberland Council',
    'Mosman Municipal Council',
    'Dubbo Regional Council',
    'Murray River Council',
    'Dungog Shire Council',
    'Murrumbidgee Council',
    'Edward River Council',
    'Muswellbrook Shire Council',
    'Eurobodalla Shire Council',
    'Nambucca Shire Council',
    'Fairfield City Council',
    'Narrabri Shire Council',
    'Federation Council',
    'Narrandera Shire Council',
    'Forbes Shire Council',
    'Narromine Shire Council',
    'Georges River Council',
    'Newcastle City Council',
    'Gilgandra Shire Council',
    'New England Weeds Authority',
    'Glen Innes Severn Council',
    'North Sydney Council',
    'Goldenfields Water County Council',
    'Northern Beaches Council',
    'Goulburn Mulwaree Council',
    'Oberon Council',
    'Greater Hume Shire Council',
    'Orange City Council',
    'Griffith City Council',
    'Parkes Shire Council',
    'Gunnedah Shire Council',
    'Penrith City Council',
    'Gwydir Shire Council',
    'Port Macquarie-Hastings Council',
    'Hawkesbury City Council',
    'Port Stephens Council',
    'Hawkesbury River County Council',
    'Queanbeyan-Palerang Council',
    'Hay Shire Council',
    'Randwick City Council',
    'Hilltops Council',
    'Richmond Valley Council',
    'Hornsby Shire Council',
    'Riverina Water County Council',
    'Hunters Hill Municipal Council',
    'Rous County Council',
    'Inner West Council',
    'Shellharbour City Council',
    'Inverell Shire Council',
    'Shoalhaven City Council',
    'Junee Shire Council',
    'Singleton Shire Council',
    'Kempsey Shire Council',
    'Snowy Monaro Regional Council',
    'Kiama Municipal Council',
    'Snowy Valleys Council',
    'Ku-ring-gai Council',
    'Strathfield Municipal Council',
    'Walgett Shire Council',
    'Sutherland Shire Council',
    'Warren Shire Council',
    'Tamworth Regional Council',
    'Warumbungle Shire Council',
    'Temora Shire Council',
    'Waverley Council',
    'Tenterfield Shire Council',
    'Weddin Shire Council',
    'The Hills Shire Council',
    'Wentworth Shire Council',
    'Tweed Shire Council',
    'Willoughby City Council',
    'Upper Hunter County Council',
    'Wingecarribee Shire Council',
    'Upper Hunter Shire Council',
    'Wollondilly Shire Council',
    'Upper Lachlan Shire Council',
    'Wollongong City Council',
    'Upper Macquarie County Council',
    'Woollahra Municipal Council',
    'Uralla Shire Council',
    'Yass Valley Council',
    'Wagga Wagga City Council',
    'Walcha Council',
    'Aboriginal and Torres Strait Islander',
    'Geographical Names Board (Customer Service)',
    'Health Practice Council (Health)',
    'ANZAC Memorial Building Trust (Communities & Justice)',
    'Housing Appeals Committee (Communities & Justice)',
    'Biodiversity Conservation Trust (PIE)',
    'Independent Planning Commission (PIE)',
    'Board of Surveying and Spatial Information (Customer Service)',
    'Jenolan Caves Reserve Trust (PIE)',
    'Building Professionals Board (Customer Service)',
    'Juvenile Justice Advisory Council (Communities & Justice)',
    'C.B. Alexander Agricultural College and',
    'Law and Justice Foundation of NSW Trust',
    'Children’s Court Clinic (Health)',
    'Law Reform Commission of NSW (Communities & Justice)',
    'Chinese Medicine Council of NSW',
    'Legal Profession Admission Board (Communities & Justice)',
    'Chiropractic Council of NSW (Health)',
    'Local Government Boundaries',
    'City West Housing (Communities & Commission (PIE)',
    'Local Government Grants Commission',
    'Cobar Water Board (PIE)',
    'Combat Sports Authority of NSW (Communities & Justice)',
    'Lord Howe Island Board (PIE)',
    'Medical Council of NSW (Health)',
    'Dams Safety Committee (PIE)',
    'Medical Radiation Practice Council of',
    'Dental Council of NSW (Health)',
    'NSW (Health)',
    'Disability Council of NSW (Communities & Justice)',
    ' Natural Resources Commission (PIE)',
    'NSW Architects Registration Board',
    'Electricity Retained Interest',
    'Ausgrid (Treasury)',
    'NSW Skills Board (Education)',
    'Electricity Retained Interest',
    'Endeavour Energy',
    'Nursing and Midwifery Council of NSW',
    'NSW State Archives and Records',
    'Occupational Therapy Council of NSW',
    'Rice Marketing Board for the State of NSW (PIE)',
    'Office of the Inspector for the Law',
    'Rookwood Necropolis Trust (PIE)',
    'Enforcement Conduct Commission (Premier & Cabinet)',
    'Sentencing Council (Communities & Justice)',
    'Office of the Inspector of the ICAC (Premier & Cabinet)',
    'Serious Offenders Review Council (Communities & Justice)',
    'Office of Transport Safety',
    'Investigations (Transport)',
    'Solicitor General and Crown Advocate (Communities & Justice)',
    'Optometry Council of NSW (Health)',
    'Veterinary Practitioners Board of NSW',
    'Osteopathy Council of NSW (Health)',
    'Parramatta Park Trust (PIE)',
    'Wentworth Park Sporting Complex Trust (PIE)',
    'Pharmacy Council of NSW (Health)',
    'Western City and Aerotropolis Authority',
    'Physiotherapy Council of NSW (Health)',
    'Podiatry Council of NSW (Health)',
    'Western Sydney Parklands Trust (PIE)',
    'Procurement Board (Treasury)',
    'Wild Dog Destruction Board (PIE)',
    'Professional Standards Authority',
    'Wine Grapes Marketing Board (PIE)',
    'Psychology Council of NSW (Health)',
    'Parliament of NSW',
    'Parliament of NSW – Legislative Council',
    'Mental Health Review Tribunal',
    'Parliament of NSW – Department of',
    'NSW Civil and Administrative Tribunal',
    'Office of the Governor',
    'NSW Coroners Court (Communities & Justice)',
    'District Court of NSW (Communities & Justice)',
    'Parliamentary Remuneration Tribunal',
    'Drug Court NSW',
    'Remuneration Tribunal',
    'Dust Diseases Tribunal',
    'Supreme Court of NSW',
    'Industrial Relations Commission of NSW (Communities & Justice)',
    'Workers\' Compensation Commission',
    'Land and Environment Court',
    'Coal Services Pty Ltd',
    'Dumaresq-Barwon Border Rivers Commission (Planning, Industry & Environment)',
    'NSW State Archives and Records'
]